### PR TITLE
Add selfupdate command to get latest version.

### PR DESCRIPTION
**Pull request by pocallaghan**
The selfupdate command will fetch the latest version number from the
website. If the version is different to the current version it will
download the latest magescan.phar file from the website.

### CODE REVIEW

**Comment by pocallaghan** [comment]
**NB:** It assumes you'll create a text file at `http://magescan.project.steverobbins.name/download/magescan-version` with just the latest version in it e.g. `1.3.2`.

**Comment by colinodell** [comment]
+1

**Comment by steverobbins** [comment]
I have the version for the latest build stored in [`/build/version`](https://github.com/steverobbins/magescan/blob/master/build/make-phar.sh#L23), I'll move it to `/public/download/version` and test.

**Comment by steverobbins** [comment]
Implemented in #75.

Thanks @pocallaghan

**Pull request closed without merging**
